Remove invalid GRUB config
'root' is not a valid GRUB command anymore. It causes GRUB to say:

  error: can't find command `root'.

  Press any key to continue...